/* *
 ! Why Java   
 * One of the most  popular programming language
 * Java currently runs on approx 60 Billion devices
 ? Wide Usage : web apps, backend, mobile apps,enterprise software
 * High paying and a lot of jobs
 ? Objected Oriented
 * Rich API's And Community support
  
 ! What is a Programming Language?
 * problem -> Human instructions -> 1010101(Binary) -> Solve
 * Giving instructions(in prog lang like java) to a computer
 ? Compiler converts high level languages to low level lang machine code

 ! What is an Algorithm ?
 * - Step by Step process 
 ! What is Syntax?
 * Structure of words in a sentence 
 ? Watching you , was i Movie ?  :D
 ? Rules of the language
 * For programming exact syntax must be followed
  
 ! originally named as 'Oak' in 1995
 * Java is developed by James Gosling at Sun Microsystems  
 ! Most important feature - "Write once run everywhere "
 * Concept with cross - platform compatibility
 ?  Latest Java version -  java 24 and java 21(LTS)
 TODO: Byte Code -> Java Bytecode is the intermediate representation of your Java code
 *   that is executed by the Java Virtual Machine (JVM). 
 *   When you compile a Java program, the Java compiler (javac)
 *   converts your code into bytecode, which is a set of instructions 
 *   that the JVM can understand and execute. This bytecode is platform-independent,
 *   meaning the same Java program can run on different devices and operating systems, 
 *   a principle known as "write once, run anywhere" (WORA).
 ? Source -> Compiler -> Output(Byte code) -> Machines
 TODO: Java Virtual Machine 
 * Benefits of java
 * 1. portability
 * 2. Security  because of java virtual machines [Only given resources are used]
 ! Buzzwords of Java
 ?1  Robust -In software engineering, robustness refers to a system's ability to maintain acceptable behavior and function correctly even when faced with invalid inputs, unexpected situations, or stressful environmental conditions. 
 * Java is robust due to its strong, memory managament , exception handling, 
 * and type checking mechanism ensuring reliable performance
 ?2. Multihreading in programming
 * is the ability of a CPU to execute multiple threads concurrently,
 *  allowing for more efficient  process and task managament
?3  Architectural Neutral
?4  Interpreted and high performance
*  as its bytecode is interpreted by java virtual machines which employs 
*  just in time compilation 
?5  Distributed
* Java is inherently distributed designed to facilitate network based application
* development and interaction , seamless integrating with internet
TODO : OBJECT Oriented Programming Language
* with focus on data , its attibutes and methods, and then we code
*   
*/ 